---
- hosts: all
  sudo: true
  vars:
    doc_root: /vagrant/web
    sys_packages: [ 'curl', 'vim', 'git']
    php_packages: [ 'php5-curl', 'php5-cli', 'php-pear', 'php5-mysql' ]
    mysql_db: vagrantee
    mysql_user: vagrantee
    mysql_pass: vagrantee
  tasks:
    - include: tasks/init.yml
    #if you prefer apache, change nginxphp.yml below to apachephp.yml
    - include: tasks/nginxphp.yml
    - include: tasks/mysql.yml
  handlers:
    - name: restart nginx
      service: name=nginx state=restarted

    - name: restart apache
      service: name=apache2 state=restarted