---
- hosts: all
  sudo: true
  vars:
    doc_root: /vagrant/web
    mysql_db: vagrantee
    mysql_user: vagrantee
    mysql_pass: vagrantee
  tasks:
    - include: tasks/init.yml
    - include: tasks/nginxphp.yml
    - include: tasks/mysql.yml
    - include: tasks/phpmodules.yml
  handlers:
    - name: restart nginx
      service: name=nginx state=restarted